name: branch_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style ic2ons.
  cupertino_icons: ^1.0.2
  get: ^4.3.8



  #firebase
  firebase_core: ^1.2.1
  cloud_firestore: ^2.5.0  #to do operation in cloud fireStore (for mobile phone)
  flutter_local_notifications: ^6.0.0
  firebase_messaging: ^10.0.1

  #chat
  bubble: ^1.2.1
  #  emoji_picker_flutter: ^1.0.6
  emoji_chooser: ^0.9.2



  #statistics helper packages
  #  fl_chart: ^0.36.3
  syncfusion_flutter_charts: ^19.2.51


  numeric_keyboard: ^1.1.0


  #slider
  carousel_pro: ^1.0.0 #used to show home page banner

  #helper packages
  email_validator: ^2.0.1 #to validate email
  country_picker: ^2.0.5 #to pick phone code (example +20)
  #  phone_code_picker: ^0.0.1 #to pick phone code (example +20) =>(last version: 0.0.2)


  #text field in otp
  code_fields: ^0.0.4
  #  pinput: ^1.2.0

  permission_handler: ^6.1.3 #used to check app permission (currently check location permission)

  #map
  place_picker: ^0.9.18
  geolocator: ^7.0.3 #to get current location
  google_maps_flutter: ^2.0.6

  #image helper

  flutter_svg: ^0.22.0

  photo_view: any #^0.11.1 #to show image with zoom  in and out

  #rating
  smooth_star_rating: ^1.1.1 #to show stars when rating

  #db
  shared_preferences: ^2.0.5 #to store app data (database alternative)

  #html
  flutter_widget_from_html_core: ^0.6.1 #used to show html code (in product view as example)

  #notifications
  toast: ^0.1.5

  #state management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1


  #to show flare files that stored in project/assets/flares/...
  flare_flutter: ^3.0.1

  #to listen to internet connection status
  flutter_offline: ^2.0.0

  #using in payment
  flutter_webview_plugin: ^0.3.11

  #date operation
  intl: ^0.17.0

  cupertino_stepper: ^0.2.0


  expandable: ^5.0.1

  bubble_tab_indicator: "^0.1.5"

  image_picker: ^0.8.1+3

  new_gradient_app_bar: ^0.2.0

  #parcode reader
  flutter_barcode_scanner: ^2.0.0 #to read barcode from camera

  #to get client signature
  signature: ^4.1.1

  share: ^2.0.4

  #counter
  numberpicker: ^2.1.1

  buttons_tabbar: ^1.3.1


  #local package
  app_routes:
    path: packages/app_routes
  http_helper:
    path: packages/http_helper
  app_launcher:
    path: packages/app_launcher

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.2
  lint: ^1.5.3
  pedantic: ^1.11.1
  pub_semver: ^2.0.0
  #  dshell:
  #  e2e:




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-BlackItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Text-UltralightItalic.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/flares/
    - assets/lang/