import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'FILTER': 'FILTER',
          'APPLY': 'apply',
          'CANCEL': 'cancel',
          'Language': 'Language',
          'Choose Language': 'Choose Language',
          'All Products': 'All Products',
          'No Products Found!': 'No Products Found!',
          'Sign Out': 'SIGN OUT',
          'HOME': 'HOME',
          'BRANCHES': 'BRANCHES',
          'Branch': 'Branch',
          'CATEGORIES': 'CATEGORIES',
          'More Details': 'More Details',
          'Choose Address': 'Choose Address',
          'Please choose that you want': 'Please choose that you want',
          'Categories': 'Categories',
          'PRODUCTS': 'PRODUCTS',
          'Products': 'Products',
          'Information': 'Information',
          'MY CART': 'MY CART',
          'MY ORDERS': 'MY ORDERS',
          'FAVOURITES': 'FAVOURITES',
          'WALLET': 'WALLET',
          'PROFILE': 'PROFILE',
          'NOTIFICATIONS': 'NOTIFICATIONS',
          'CHAT': 'CHAT',
          'LANGUAGES': 'LANGUAGES',
          'HELP & SUPPORT': 'HELP & SUPPORT',
          'Help & Support': 'Help & Support',
          'Contact Us': 'Contact Us',
          'CONTACT US': 'CONTACT US',
          'ABOUT US': 'ABOUT US',
          'About Us': 'About Us',
          'DELIVERY INFO': 'DELIVERY INFO',
          'Delivery Info': 'Delivery Info',
          'PRIVACY POLICY': 'PRIVACY POLICY',
          'Privacy Policy': 'Privacy Policy',
          'Terms And Conditions': 'Terms And Conditions',
          'TERMS AND CONDITION': 'TERMS AND CONDITION',
          'REFUND POLICY': 'REFUND POLICY',
          'Refund Policy': 'Refund Policy',
          'No Branches Found!': 'No Branches Found!',
          'All Branches': 'All Branches',
          'Select Country': 'Select Country',
          'No countries available': 'No countries available',
          'Search For Your Country': 'Search For Your Country',
          'Select State': 'Select State',
          'No States available': 'No States available',
          'Search For Your State': 'Search For Your State',
          'Saved Addresses': 'Saved Addresses',
          'No Addresses Found!': 'No Addresses Found!',
          'Add New Address': 'Add New Address',
          'Forget Password': 'Forget Password',
          'EMAIL ADDRESS': 'EMAIL ADDRESS',
          'My Addresses': 'My Addresses',
          'Change Password': 'Change Password',
          'Send': 'Send',
          "Didn't receive?": "Didn't receive?",
          'Send Again': 'Send Again',
          'Please complete the code': 'Please complete the code',
          'Please enter a valid code': 'Please enter a valid code',
          'Confirmation': 'Confirmation',
          'Continue': 'Continue',
          "don't get it?": "don't get it?",
          'Resend code': 'Resend code',
          'Welcome': 'Welcome',
          'Login': 'Login',
          'FORGET_PASS': 'Forget Password ?',
          'Sign Up': 'Sign Up',
          'PASSWORD': 'PASSWORD',
          'FULL NAME': 'FULL NAME',
          'PHONE NUMBER': 'PHONE NUMBER',
          'CONFIRM PASSWORD': 'CONFIRM PASSWORD',
          'Confirm': 'Confirm',
          'Country': 'Country',
          'State': 'State',
          'You must Select Country First': 'You must Select Country First',
          'already have account?': 'already have account?',
          'Sign in': 'Sign in',
          'SIGN IN': 'SIGN IN',
          'need an account?': 'need an account?',
          'km': 'km',
          'Top Branch': 'Top Branch',
          'Cart View': 'Cart View',
          'عربة التسوق': 'عربة التسوق',
          'Not Available': 'Not Available',
          'Available In Another Branch': 'Available In Another Branch',
          'Clear Cart': 'Clear Cart',
          'Check Out': 'Check Out',
          'Total': 'Total',
          'Taxes': 'Taxes',
          'Subtotal': 'Subtotal',
          'Add To Cart': 'Add To Cart',
          'Not Available in any branch': 'Not Available in any branch',
          'Available In Another Branch\nclear cart to add this product':
              'Available In Another Branch\nclear cart to add this product',
          'small amount': 'small amount',
          'Amount': 'Amount',
          'available': 'available',
          'All Categories': 'All Categories',
          'No Categories Found!': 'No Categories Found!',
          'No Products yet!': 'No Products yet!',
          'No Data Found!': 'No Data Found!',
          'SEE ALL': 'SEE ALL',
          'Location': 'Location',
          'PHONE': 'PHONE',
          'Phone': 'Phone',
          'E-mail': 'E-mail',
          'Social Media': 'Social Media',
          'Website': 'Website',
          'Twitter': 'Twitter',
          'Facebook': 'Facebook',
          'LinkedIn': 'LinkedIn',
          'Youtube': 'Youtube',
          'Instagram': 'Instagram',
          'No Faq Found!': 'No Faq Found!',
          'Favourite List': 'Favourite List',
          'No Items Found!': 'No Items Found!',
          'Internet Connection Error!': 'Internet Connection Error!',
          'Try Again': 'Try Again',
          'You Must Sign In To Allow You To Enter This Page':
              'You Must Sign In To Allow You To Enter This Page',
          'Go To Home Page': 'Go To Home Page',
          'Access Denied!': 'Access Denied!',
          'Go Back To Continue': 'Go Back To Continue',
          'Notifications': 'Notifications',
          'Reviews': 'Reviews',
          'No Notifications Found!': 'No Notifications Found!',
          'Description': 'Description',
          'Payment View': 'Payment View',
          'USER NAME': 'USER NAME',
          'Edit Account': 'Edit Account',
          'Your Rating': 'Your Rating',
          'Write a Review': 'Write a Review',
          'Submit': 'Submit',
          'Write Your Review Here': 'Write Your Review Here',
          'Your Review': 'Your Review',
          'No Reviews Found!': 'No Reviews Found!',
          'Review': 'Review',
          'Reset Password': 'Reset Password',
          'Old Password': 'Old Password',
          'New Password': 'New Password',
          'Save': 'Save',
          'Unknown Exception': 'Unknown Exception',
          'Check Order': 'Check Order',
          'Orders': 'Orders',
          'No Orders Found!': 'No Orders Found!',
          'My Order': 'My Order',
          "STATISTICS": "Statistics",
          'TOTAL_COLLECTED': 'Total Collected',
          'TOTAL_EARNING': 'Total Earning',
          'WELCOME_BACK': 'Welcome Back,',
          'NUMBER_OF_ORDERS': 'Number Of Orders',
          'IN_DELIVERY_ORDERS': 'In Delivery Orders',
          'ORDERS': 'Orders',
          'ORDER_ID': 'Order ID #',
          'UNKNOWN': 'UnKnown',
          'AN_ERROR_HAS_OCCURRED': 'An Error Has Occurred',
          'FROM': 'From',
          'TO': 'To',
          'SHOW_ALL_STATISTICS': 'Show All Statistics',
          "ALL": "ALL",
          "DONE": "Done",
          "IN_DELIVERY": "In Delivery",
          "SUPPORT": "Support",
          "NO_USERS_FOUND": "No User Found !",
          "EXPENDITURE_SUMMARY": "Expenditure Summary",
          "INCOME": "Income",
          "AT_A_GLANCE": "At A Glance",
          "IN_BRANCH": "In Branch",
          "ONLINE": "Online",
          "NEW_ORDERS": "New Orders",
          "DRIVERS_LIST": "DRIVERS LIST",
          "ADD_PRODUCT": "ADD PRODUCT",
          "HISTORY": "HISTORY",
          "DELIVERY_MEN": "Delivery Men",
          "HAVE_ORDERS": "Have Orders",
          "HAVENT_ORDERS": "Haven't Orders",
          "WRITE_BARCODE": "Write barcode",
          "CLICK_TO_READ": "Click To Read Barcode",
        },
        'ar': {
          "AT_A_GLANCE": "لمحة سريعة",
          "IN_BRANCH": "فى فرع",
          "ONLINE": "عبر الانترنت",
          "NEW_ORDERS": "طلبات جديدة",
          "DRIVERS_LIST": "قائمة السواقين",
          "ADD_PRODUCT": "اضافة منتج",
          "DELIVERY_MEN": "رجال التوصيل",
          "HISTORY": "سجل الطلبات",
          "HAVE_ORDERS": "لدية طلبات",
          "HAVENT_ORDERS": "ليس لدية طلبات",
          "WRITE_BARCODE": "اكتب الباركود",
          "CLICK_TO_READ": "اضغط لقراءة الباركود",
          "STATISTICS": "الاحصائيات",
          'TOTAL_COLLECTED': 'المجموع الكلى',
          'TOTAL_EARNING': 'اجمالى المكسب',
          'WELCOME_BACK': 'مرحبا بعودتك ,',
          'NUMBER_OF_ORDERS': 'عدد الطلبات',
          'IN_DELIVERY_ORDERS': 'طلبات التوصيل',
          "EXPENDITURE_SUMMARY": "ملخص المصروفات",
          "INCOME": "الدخل",
          'ORDERS': 'طلبات',
          'ORDER_ID': 'رقم الطلب #',
          'UNKNOWN': 'غير معروف',
          "FILTER": "تصفية",
          "APPLY": "تطبيق",
          "CANCEL": "الغاء",
          "Language": "اللغة",
          "Choose Language": "إختار اللغة",
          "All Products": "جميع المنتجات",
          "No Products Found!": "لا توجد منتجات",
          "Sign Out": "تسجيل الخروج",
          "HOME": "الشاشة الرئيسية",
          "BRANCHES": "الفروع",
          "Branch": "الفرع",
          "CATEGORIES": "الأقسام",
          "More Details": "تفاصيل أكثر",
          "Choose Address": "إختار عنوان",
          'AN_ERROR_HAS_OCCURRED': 'حدث خطاء ما',
          'FROM': 'من',
          'TO': 'الى',
          'SHOW_ALL_STATISTICS': 'اظهار كل الاحصائيات',
          "More": "المزيد",
          "ALL": "الكل",
          "DONE": "تم",
          "IN_DELIVERY": "جارى التوصيل",
          "SUPPORT": "الدعم",
          "NO_USERS_FOUND": "لا يوجد مستخدمين",
          "Please choose that you want": "الرئيسي",
          "Categories": "الأقسام",
          "PRODUCTS": "المنتجات",
          "Products": "منتجات",
          "Information": "معلومات",
          "MY CART": "عربتى",
          "MY ORDERS": "طلباتى",
          "FAVOURITES": "المفضلة",
          "WALLET": "المحفظة",
          "PROFILE": "الملف الشخصى",
          "NOTIFICATIONS": "الإشعارات",
          "CHAT": "محادثة",
          "LANGUAGES": "اللغات",
          "HELP & SUPPORT": "المساعدة والدعم",
          "Help & Support": "المساعدة والدعم",
          "Contact Us": "تواصل معنا",
          "CONTACT US": "تواصل معنا",
          "ABOUT US": "معلومات عنا",
          "About Us": "معلومات عنا",
          "DELIVERY INFO": "معلومات التوصيل",
          "Delivery Info": "معلومات التوصيل",
          "PRIVACY POLICY": "سياسة الخصوصية",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms And Conditions": "الأحكام والشروط",
          "TERMS AND CONDITION": "الأحكام والشروط",
          "REFUND POLICY": "سياسة الإسترجاع",
          "Refund Policy": "سياسة الإسترجاع",
          "No Branches Found!": "لا يوجد أى فروع",
          "All Branches": "جميع الفروع",
          "Select Country": "حدد الدولة",
          "No countries available": "لا توجد دول متاحة",
          "Search For Your Country": "إبحث عن بلدك",
          'Select State': 'إختر الولاية',
          'No States available': 'لا توجد دول متاحة',
          'Search For Your State': 'إبحث عن دولتك',
          'Saved Addresses': 'العناوين المحفوظة',
          'No Addresses Found!': 'لا توجد عناوين',
          'Add New Address': 'إضافة عنوان جديد',
          'Forget Password': 'نسيت كلمة السر',
          'EMAIL ADDRESS': 'عنوان البريد الإلكترونى',
          'My Addresses': 'عنوانينى',
          'Change Password': 'تغير كلمة المرور',
          'Send': 'إرسال',
          "Didn't receive?": "لم تستلم؟",
          'Send Again': 'إعد الإرسال',
          'Please complete the code': 'من فضلك أكمل الكود',
          'Please enter a valid code': 'الرجاء إدخال الكود الصحيح',
          'Confirmation': 'تأكيد',
          'Continue': 'إستمرار',
          "don't get it?": "لم تستلم بعد؟",
          'Resend code': 'إعادة إرسال',
          'Welcome': 'مرحبا',
          'Login': 'تسجيل دخول',
          'FORGET_PASS': 'نسيت كلمة المرور ؟',
          'Sign Up': 'إنشاء حساب',
          'PASSWORD': 'كلمة المرور',
          'FULL NAME': 'الإسم بالكامل',
          'PHONE NUMBER': 'رقم الهاتف',
          'CONFIRM PASSWORD': 'تأكيد كلمة المرور',
          'Confirm': 'تأكيد',
          'Country': 'بلد',
          'State': 'دولة',
          'You must Select Country First': 'يجب تحديد الدولة أولا',
          'already have account?': 'تمتلك حساب بالفعل؟',
          'Sign in': 'تسجيل الدخول',
          'SIGN IN': 'تسجيل الدخول',
          'need an account?': 'تحتاج لإنشاء حساب',
          'km': 'كم',
          'Top Branch': 'أعلى تقييم',
          'Cart View': 'عربة التسوق',
          'Not Available': 'غير متوفر',
          'Available In Another Branch': 'متوفر فى فرع أخر',
          'Clear Cart': 'محو السلة',
          'Check Out': 'الدفع',
          'Total': 'المجموع',
          'Taxes': 'ضرائب',
          'Subtotal': 'المجموع',
          'Add To Cart': 'أضف إلى العربة',
          'Not Available in any branch': 'غير متوفر فى الفروع',
          'Available In Another Branch\nclear cart to add this product':
              'متوفر فى فرع غير المختار فى عربة التسوق\n مسح عربة التسوق',
          'small amount': 'كمية قليلة',
          'Amount': 'كمية',
          'available': 'متوفر',
          'All Categories': 'جميع الأقسام',
          'No Categories Found!': 'لا توجد أقسام',
          'No Products yet!': 'لا توجد منتجات',
          'No Data Found!': 'لا توجد بيانات',
          'SEE ALL': 'عرض الكل',
          'Location': 'الموقع',
          'PHONE': 'الهاتف',
          'Phone': 'الهاتف',
          'E-mail': 'عنوان البريد الإلكترونى',
          'Social Media': 'وسائل التواصل الإجتماعى',
          'Website': 'الموقع الإلكترونى',
          'Twitter': 'تويتر',
          'Facebook': 'فيس بوك',
          'LinkedIn': 'لينكد إن',
          'Youtube': 'يوتيوب',
          'Instagram': 'إنستجرام',
          'No Faq Found!': 'لا توجد أسالة شائعة',
          'Favourite List': 'قائمة العناصر المفضلة',
          'No Items Found!': 'لا توجد عناصر',
          'Internet Connection Error!': 'خطأ فى الاتصال بالانترنت',
          'Try Again': 'حاول مجددا',
          'You Must Sign In To Allow You To Enter This Page':
              'يجب عليك تسجيل الدخول للسماح لك بالدخول إلى هذه الصفحة',
          'Go To Home Page': 'الذهاب إلى الصفحة الرئيسية',
          'Access Denied!': 'طلب مرفوض',
          'Go Back To Continue': 'العودة للمتابعة',
          'Notifications': 'الإشعارات',
          'Reviews': 'المراجعات',
          'No Notifications Found!': 'لا توجد إشعارات',
          'Description': 'الوصف',
          'Payment View': 'شاشة الدفع',
          'USER NAME': 'إسم المستخدم',
          'Edit Account': 'تعديل بيانات الحساب',
          'Your Rating': 'تقييمك',
          'Write a Review': 'أكتب تعليقك',
          'Submit': 'إرسال',
          'Write Your Review Here': 'أكتب تقييمك هنا',
          'Your Review': 'تقييمك',
          'No Reviews Found!': 'لا توجد مراجعات بعد',
          'Review': 'تقييم',
          'Reset Password': 'إعادة تعيين كلمة المرور',
          'Old Password': 'كلمة المرور القديمة',
          'New Password': 'كلمة المرور الجديدة',
          'Save': 'حفظ',
          'Unknown Exception': 'حدث خطأ غير متوقع',
          'Check Order': 'مراجعة الطلب',
          'Orders': 'طلباتى',
          'No Orders Found!': 'لا توجد طلبات!',
          'My Order': 'طلبى',
        }
      };
}
